CREATE TABLE IF NOT EXISTS medical_specializations (
    specialization_id SERIAL PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    description TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO medical_specializations (name, description)
VALUES
('Allergy and Immunology', 'Immune system conditions, allergies, and asthma.'),
('Anesthesiology', 'Anesthesia, perioperative care, and pain control.'),
('Audiology', 'Hearing, balance, and related ear conditions.'),
('Bariatric Medicine', 'Medical care for obesity and weight management.'),
('Cardiology', 'Heart and vascular system health.'),
('Cardiothoracic Surgery', 'Surgery for heart, lungs, and chest organs.'),
('Critical Care Medicine', 'Care for life-threatening illness and ICU patients.'),
('Dentistry', 'Teeth, gums, and oral health care.'),
('Dermatology', 'Skin, hair, and nail conditions.'),
('Endocrinology', 'Hormones, diabetes, thyroid, and metabolic conditions.'),
('ENT', 'Ear, nose, throat, sinus, and voice conditions.'),
('Family Medicine', 'Whole-family primary care across all ages.'),
('Gastroenterology', 'Digestive tract, liver, and pancreas care.'),
('General Medicine', 'Primary adult medical care and common illnesses.'),
('General Surgery', 'Surgical care for common abdominal and soft tissue problems.'),
('Geriatrics', 'Medical care focused on older adults.'),
('Gynecology', 'Women''s reproductive and pelvic health.'),
('Hematology', 'Blood disorders and clotting conditions.'),
('Hepatology', 'Liver, gallbladder, and bile duct conditions.'),
('Infectious Disease', 'Complex infections and antimicrobial care.'),
('Internal Medicine', 'Adult diagnosis, treatment, and preventive care.'),
('Neonatology', 'Medical care for newborns and premature infants.'),
('Nephrology', 'Kidney disease, dialysis, and blood pressure care.'),
('Neurology', 'Brain, spine, nerve, and nervous system disorders.'),
('Neurosurgery', 'Surgery for brain, spine, and nerve disorders.'),
('Nutrition and Dietetics', 'Diet planning, clinical nutrition, and wellness.'),
('Obstetrics', 'Pregnancy, childbirth, and postpartum care.'),
('Obstetrics and Gynecology', 'Pregnancy and women''s reproductive health.'),
('Oncology', 'Cancer diagnosis, treatment, and follow-up care.'),
('Ophthalmology', 'Eye disease, vision care, and eye surgery.'),
('Orthopedics', 'Bones, joints, ligaments, and musculoskeletal care.'),
('Pain Medicine', 'Diagnosis and treatment of acute and chronic pain.'),
('Pathology', 'Laboratory diagnosis of disease.'),
('Pediatrics', 'Medical care for infants, children, and adolescents.'),
('Physical Medicine and Rehabilitation', 'Recovery, mobility, and functional rehabilitation.'),
('Plastic Surgery', 'Reconstructive and cosmetic surgical care.'),
('Psychiatry', 'Mental health, behavior, and medication management.'),
('Psychology', 'Therapy, testing, and behavioral health support.'),
('Pulmonology', 'Lung and breathing conditions.'),
('Radiology', 'Medical imaging and image-guided diagnosis.'),
('Rheumatology', 'Autoimmune, joint, and connective tissue disorders.'),
('Sleep Medicine', 'Sleep disorders, insomnia, and sleep apnea.'),
('Sports Medicine', 'Exercise injuries, performance, and musculoskeletal health.'),
('Urology', 'Urinary tract and male reproductive health.'),
('Vascular Surgery', 'Surgery for arteries, veins, and circulation problems.')
ON CONFLICT (name) DO UPDATE
SET description = EXCLUDED.description,
    is_active = TRUE,
    updated_at = CURRENT_TIMESTAMP;
