import {
  appointmentApi,
  blogApi,
  chatApi,
  historyApi,
  medicationApi,
  notificationApi,
  prescriptionApi,
  vitalApi,
  forumApi,
  userApi,
} from "../utils/apiHelper";

export const doctorService = {
  getPatients: () => userApi.list(),
  getAppointments: (doctorId) => appointmentApi.byDoctor(doctorId),
  updateAppointmentStatus: (id, status) =>
    appointmentApi.updateStatus(id, status),
  getVitals: (patientId) => vitalApi.byPatient(patientId),
  getAlerts: (patientId) => vitalApi.alerts(patientId),
  addVital: (payload) => vitalApi.create(payload),
  getHistory: (patientId) => historyApi.byPatient(patientId),
  addHistory: (payload) => historyApi.create(payload),
  getPrescriptions: (patientId) => prescriptionApi.byPatient(patientId),
  createPrescription: (payload) => prescriptionApi.createMaster(payload),
  addPrescriptionMedication: (payload) => prescriptionApi.addMedication(payload),
  listMedications: () => medicationApi.list(),
  createMedicationLog: (payload) => medicationApi.createLog(payload),
  getMedicationLogs: (patientId) => medicationApi.byPatientLogs(patientId),
  updateMedicationLog: (logId, payload) => medicationApi.updateLogStatus(logId, payload),
  getInbox: (userId) => chatApi.inbox(userId),
  findOrCreateRoom: (payload) => chatApi.findOrCreateRoom(payload),
  sendMessage: (payload) => chatApi.sendMessage(payload),
  getChatMessages: (roomId) => chatApi.roomMessages(roomId),
  getPendingBlogs: () => blogApi.pending(),
  getBlogs: () => blogApi.feed(),
  createBlog: (payload) => blogApi.create(payload),
  likeBlog: (payload) => blogApi.like(payload),
  commentBlog: (payload) => blogApi.comment(payload),
  bookmarkBlog: (payload) => blogApi.bookmark(payload),
  getForumPosts: () => forumApi.feed(),
  createForumPost: (payload) => forumApi.createPost(payload),
  getForumPost: (postId) => forumApi.getPost(postId),
  replyForumPost: (payload) => forumApi.reply(payload),
  reportForumPost: (payload) => forumApi.report(payload),
  notifyPatient: (payload) => Promise.resolve({ data: "not implemented" }),
};

export default doctorService;
