const SPECIALIZATIONS = [
  { name: "Allergy and Immunology", description: "Immune system conditions, allergies, and asthma." },
  { name: "Anesthesiology", description: "Anesthesia, perioperative care, and pain control." },
  { name: "Audiology", description: "Hearing, balance, and related ear conditions." },
  { name: "Bariatric Medicine", description: "Medical care for obesity and weight management." },
  { name: "Cardiology", description: "Heart and vascular system health." },
  { name: "Cardiothoracic Surgery", description: "Surgery for heart, lungs, and chest organs." },
  { name: "Critical Care Medicine", description: "Care for life-threatening illness and ICU patients." },
  { name: "Dentistry", description: "Teeth, gums, and oral health care." },
  { name: "Dermatology", description: "Skin, hair, and nail conditions." },
  { name: "Endocrinology", description: "Hormones, diabetes, thyroid, and metabolic conditions." },
  { name: "ENT", description: "Ear, nose, throat, sinus, and voice conditions." },
  { name: "Family Medicine", description: "Whole-family primary care across all ages." },
  { name: "Gastroenterology", description: "Digestive tract, liver, and pancreas care." },
  { name: "General Medicine", description: "Primary adult medical care and common illnesses." },
  { name: "General Surgery", description: "Surgical care for common abdominal and soft tissue problems." },
  { name: "Geriatrics", description: "Medical care focused on older adults." },
  { name: "Gynecology", description: "Women's reproductive and pelvic health." },
  { name: "Hematology", description: "Blood disorders and clotting conditions." },
  { name: "Hepatology", description: "Liver, gallbladder, and bile duct conditions." },
  { name: "Infectious Disease", description: "Complex infections and antimicrobial care." },
  { name: "Internal Medicine", description: "Adult diagnosis, treatment, and preventive care." },
  { name: "Neonatology", description: "Medical care for newborns and premature infants." },
  { name: "Nephrology", description: "Kidney disease, dialysis, and blood pressure care." },
  { name: "Neurology", description: "Brain, spine, nerve, and nervous system disorders." },
  { name: "Neurosurgery", description: "Surgery for brain, spine, and nerve disorders." },
  { name: "Nutrition and Dietetics", description: "Diet planning, clinical nutrition, and wellness." },
  { name: "Obstetrics", description: "Pregnancy, childbirth, and postpartum care." },
  { name: "Obstetrics and Gynecology", description: "Pregnancy and women's reproductive health." },
  { name: "Oncology", description: "Cancer diagnosis, treatment, and follow-up care." },
  { name: "Ophthalmology", description: "Eye disease, vision care, and eye surgery." },
  { name: "Orthopedics", description: "Bones, joints, ligaments, and musculoskeletal care." },
  { name: "Pain Medicine", description: "Diagnosis and treatment of acute and chronic pain." },
  { name: "Pathology", description: "Laboratory diagnosis of disease." },
  { name: "Pediatrics", description: "Medical care for infants, children, and adolescents." },
  { name: "Physical Medicine and Rehabilitation", description: "Recovery, mobility, and functional rehabilitation." },
  { name: "Plastic Surgery", description: "Reconstructive and cosmetic surgical care." },
  { name: "Psychiatry", description: "Mental health, behavior, and medication management." },
  { name: "Psychology", description: "Therapy, testing, and behavioral health support." },
  { name: "Pulmonology", description: "Lung and breathing conditions." },
  { name: "Radiology", description: "Medical imaging and image-guided diagnosis." },
  { name: "Rheumatology", description: "Autoimmune, joint, and connective tissue disorders." },
  { name: "Sleep Medicine", description: "Sleep disorders, insomnia, and sleep apnea." },
  { name: "Sports Medicine", description: "Exercise injuries, performance, and musculoskeletal health." },
  { name: "Urology", description: "Urinary tract and male reproductive health." },
  { name: "Vascular Surgery", description: "Surgery for arteries, veins, and circulation problems." },
];

module.exports = SPECIALIZATIONS;
